# Generated by Django 6.0.2 on 2026-02-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_profile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20),
        ),
    ]
